### PR TITLE
Try to keep using atomic operations for data more

### PR DESCRIPTION
**Pull request by nanonyme**
Instead of making backup, let's just make sure we use enough atomic operations that if things break, we will eventually land in consistent state.

### CODE REVIEW

**Comment by nanonyme** [comment]
@gasinvein do you have time to review? I rewrote the entire data migration part to try to make more parts of it atomic.

**Comment by gasinvein** [comment]
Can you please explain when and why does copying fail currently?

**Comment by nanonyme** [comment]
@gasinvein the copytree fails on Steam Runtime iirc (the Ubuntu stuff inside Steam installation directory).

**Comment by gasinvein** [comment]
You mean during backup stage (i.e. since c25fdcadcb2dfeac6f297c2cbc47f28b8390dfbb), or else?
It didn't fail for me neither before nor after recent changes. Yet I have no games in the default library, not sure if that matters.

**Comment by nanonyme** [comment]
At least those were the experiences way back when this was first written. Anyway, the intent is we overwrite target with what was in source. Target can exist, that is fine. We don't need backup at that point. The problem is the source which needs to be replaced with a symlink. If you start Steam without steam-wrapper, then Steam will write there.

**Comment by nanonyme** [comment]
I'm actually potentally also confused. Maybe target is smaller and safe to just backup.

**Comment by nanonyme** [comment]
I'll do one round of testing. If everything seems good, I'll roll a release still today without these changes.

**Comment by nanonyme** [comment]
Turns out the migration doesn't actually work as is. But I don't think your change broke it any worse.

**Comment by gasinvein** [comment]
Sorry, I fail to understand how this PR changes target-related behavior. In both cases we end up `cypytree`'ing `~/.var/app/com.valvesoftware.Steam/data` to `~/.var/app/com.valvesoftware.Steam/.local/share`, except for that now we move the former aside before copying.

**Comment by nanonyme** [comment]
Basically the idea in this PR was doing the symlink *first*. If the older code fails at making the symlink (which should not break hopefully?), it will already have migrated everything so next run will copy dozens of gigabytes of files to a new directory.

**Comment by nanonyme** [comment]
Closing, will proceed with a release.

**Pull request closed without merging**
