### PR TITLE
Upgrade to a newer NSS to fix Store display

### LINKED ISSUE #47: Fix empty store (requires nss 3.26)
I suspect there was a recent update to the external Steam application, and it now has a dependency on nss >= 3.26, but the freedesktop 1.6 runtime has nss 3.25.

This causes the store to be empty:

screenshot from 2017-12-14 23-15-28

with errors such as the following repeated in the journal every 10 seconds:
```
Dec 14 23:15:20 endless com.valvesoftware.Steam.desktop[1702]: [1214/231520.336090:ERROR:proxy_config_service_linux.cc(274)] Error requesting gconf directory: Failed to activate configuration server: org.freedesktop.DBus.Error.ServiceUnknown
Dec 14 23:15:20 endless com.valvesoftware.Steam.desktop[1702]: [1214/231520.336468:FATAL:nss_util.cc(632)] NSS_VersionCheck("3.26") failed. NSS >= 3.26 is required. Please upgrade to the latest NSS, and if you still get this error, contact your distribution maintainer.
Dec 14 23:15:20 endless com.valvesoftware.Steam.desktop[1702]: /sysroot/home/roddy/.var/app/com.valvesoftware.Steam/data/Steam/ubuntu12_64/steamwebhelper.sh: line 5:   268 Aborted                 (core dumped) ./steamwebhelper "$@"
```

I confirmed that copying libnss3.so from a 3.26 build of nss into /var/lib/flatpak/app/com.valvesoftware.Steam/x86_64/stable/active/files/lib fixed the problem.

### PR DESCRIPTION
**Pull request by nedrichards**
Should fix #47 

This initially copies the section from com.spotify.Spotify, since that should actually have received some testing but this may need further attention.

### CODE REVIEW

**Comment by nedrichards** [comment]
bot, build

**Comment by nedrichards** [comment]
bot, build

**Comment by nanonyme** [comment]
Agrees on needing attention. Needing to bundle dep in many apps smells like problem in runtime

**Comment by nedrichards** [comment]
There will be a new FDo runtime at some point fairly soon, which will update a lot of things. Certainly getting GCC7 in a runtime would be helpful for some apps, but that's more of an issue for https://github.com/flatpak/freedesktop-sdk-images

**Comment by nedrichards** [comment]
@nanonyme can you merge this? or is there anything more you want done? I've confirmed that this fixes the issue in local testing.

**Comment by nedrichards** [comment]
OK - since this fixes a highly user visible issue and has been tested to be OK I'm going to merge, but happy to take post-hoc review/fixes as necessary.

**Pull request merged**
