### PR TITLE
Merge beta to master

### PR DESCRIPTION
**Pull request by bbhtt**
This should be merged after the beta branch has gone through some testing with 24.08, so a few weeks later.

### CODE REVIEW

**Comment by nanonyme** [comment]
Maybe time to land this?

**Comment by AsciiWolf** [comment]
Any chance it could be merged now? :-)

**Comment by AsciiWolf** [comment]
bot, build

**Comment by AsciiWolf** [comment]
screenshot

screenshot2

I am on my laptop with integrated GPU so I was not able to try any more demanding games, but everything I tested (both native and Proton) worked fine (or crashed just like it does on 23.08 :)). The Steam client itself also worked fine including all its functions that I tried.

I think that this PR is **ready to be merged**.

**Comment by bbhtt** [comment]
> I think that this PR is ready to be merged.

You have to wait, barthalion is away on vacation and I'm busy with everything else. I'll merge it.

**Pull request closed without merging**
