### PR TITLE
Make beta use future 19.08

### PR DESCRIPTION
**Pull request by nanonyme**

### CODE REVIEW

**Comment by LeandroStanger** [comment]
bot, build com.valvesoftware.Steam

**Comment by nanonyme** [comment]
Please don't rebuild. Flathub doesn't currently support beta Sdk.

**Comment by gasinvein** [comment]
Is FD.o runtime 19.08 already available from Flathub?

**Comment by barthalion** [comment]
bot, build

**Comment by barthalion** [comment]
bot, build

**Comment by gasinvein** [comment]
Excuse me for off-topic, but what do I need for flathub/net.lutris.Lutris#7 to use the beta runtime?

**Comment by nanonyme** [comment]
<3 @valentindavid should I merge this as is or wait for next beta release and remove the SDL patch? I'm incapable of doing latter for a week.

**Comment by nanonyme** [comment]
I think I'll just let this fly :)

**Pull request merged**
