### PR TITLE
Fix Civilization 6

### PR DESCRIPTION
**Pull request by valentindavid**
This depends on:
https://gitlab.com/freedesktop-sdk/freedesktop-sdk/merge_requests/1157
Which depends on:
https://gitlab.com/freedesktop-sdk/shared-library-guard/merge_requests/6

### CODE REVIEW

**Comment by sat3ll** [comment]
Both of the PRs mentioned have been merged already. Is there anything blocking this from being merged?

**Comment by nanonyme** [comment]
This is a runtime 19.08 feature.

**Comment by nanonyme** [comment]
Theoretically no. Currently this is conflicted currently.

**Comment by nanonyme** [comment]
@sat3ll keep in mind this is not for now enabled by default

**Pull request merged**
