### PR TITLE
Support for translations PT-BR and ES

### PR DESCRIPTION
**Pull request by LeandroStanger**

### CODE REVIEW

**Review by nanonyme — COMMENTED** [review]
Why was the slash changed to plus?

**Comment by LeandroStanger** [comment]
captura de tela de 2018-06-08 11-11-01

**Comment by TingPing** [comment]
bot, build

**Comment by TingPing** [comment]
Invalid XML: https://flathub.org/builds/#/builders/28/builds/270

**Comment by LeandroStanger** [comment]
bot, build

**Comment by nanonyme** [comment]
bot, build

**Pull request merged**
