### PR TITLE
Add reference to old desktop ID

### PR DESCRIPTION
**Pull request by AsciiWolf**
See [this comment](https://github.com/flathub/net.sourceforge.Fillets/issues/4#issue-436137709).

### CODE REVIEW

**Comment by nanonyme** [comment]
I'm not sure this is ok. Valve doesn't officially support this application and their stand is this is fine as long as people won't confuse it with official Flatpak.

**Comment by AsciiWolf** [comment]
Hmm, I am not sure if this is an issue. Flathub is not enabled by default on most distributions and Flatpak is not even installed by default on Ubuntu. Also, almost every distribution has its own Steam package. Are those supported?

Anyway, with the correct old desktop ID, Steam can be displayed as one entry in GNOME Software (since 3.32) and user can easily select which repository source they want to choose. Without the old desktop ID, it is displayed as multiple entries and it is actually confusing for the user.

@hughsie What is your opinion about this?

**Comment by hughsie** [comment]
> What is your opinion about this?

It needs the patch as suggested by @AsciiWolf -- **it's the same app** -- any developer information about who packaged it, or who supplied the binaries is component information that is shown in the software center as extra information.

**Comment by gasinvein** [comment]
Isn't `rename-desktop-file` enough? flatpak-builder adds a `X-Flatpak-RenamedFrom` entry to the .desktop file, which is read by gnome-software to identify same app.

**Comment by AsciiWolf** [comment]
@gasinvein Hmm, I am not sure. Maybe @hughsie will know more. :-)

**Comment by gasinvein** [comment]
@AsciiWolf well, at least for me gnome-software already correctly identifies Steam from different sources as being the same app:
Screenshot 2019-05-03 15-10-45

**Comment by AsciiWolf** [comment]
Interesting.

**Comment by AsciiWolf** [comment]
@hughsie @alexlarsson Is the `rename-desktop-file` enough or should there be the old desktop ID added to the AppData file?

**Comment by AsciiWolf** [comment]
@gasinvein I just tried it on Fedora 30. You're right, it works fine even without the old desktop ID reference in AppData.

**Pull request closed without merging**
