### PR TITLE
Update compatibility tools support

### PR DESCRIPTION
**Pull request by gasinvein**
Valve has added support for compatibility tools installed system-wide in current Steam Beta https://github.com/ValveSoftware/steam-for-linux/issues/6310#issuecomment-544279123
We can now stop re-writing ct manifests into users home directory via the wrapper.

### CODE REVIEW

**Comment by nanonyme** [comment]
Do you have some compat tool available that you can test this with?

**Comment by gasinvein** [comment]
@nanonyme Yes, I'm currently testing this with Boxtron.

**Comment by gasinvein** [comment]
Seems like it's working.

@nanonyme AFAIK Steam support compatibility tools in two layouts:

- one with the tools placed in a subdirectory (e.g. `compatibitytools.d/Boxtron/compatibilitytool.vdf`)
- and the other without a subdirectory (e.g.  `compatibitytools.d/boxtron.vdf`)

Should we support both? I guess Flatpak's `merge-dirs` could help with that.

**Comment by nanonyme** [comment]
Dunno. If this is fine, I'm going to land this. Can be extended later. This simplifies wrapper which is always a good thing.

**Comment by gasinvein** [comment]
I believe this could be merged into stable, too. "Beta" here mans Steam client beta, it's opt-in in the client regardless of the flatpak branch.

**Comment by nanonyme** [comment]
I'd prefer to get that one more SDL2 quirk file added before doing another release.

**Pull request merged**
