### PR TITLE
Fix mesa_shader_workaround

### LINKED ISSUE #155: steam-wrapper makes incorrect assumption that current working directory is always home
Hi I have clean installation of steam via flatpak and I have problem with running steam
```
flatpak run com.valvesoftware.Steam
Traceback (most recent call last):
  File "/app/bin/steam-wrapper", line 11, in <module>
    load_entry_point('steam-wrapper==1.0.0', 'console_scripts', 'steam-wrapper')()
  File "/app/lib/python3.7/site-packages/steam_wrapper.py", line 229, in main
    mesa_shader_workaround()
  File "/app/lib/python3.7/site-packages/steam_wrapper.py", line 49, in mesa_shader_workaround
    shutil.copy2(candidate, current)
  File "/usr/lib/python3.7/shutil.py", line 257, in copy2
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/usr/lib/python3.7/shutil.py", line 121, in copyfile
    with open(dst, 'wb') as fdst:
FileNotFoundError: [Errno 2] No such file or directory: '/home/t0ki/.var/app/com.valvesoftware.Steam/.config/.flatpak-info'
```
It looks like some files are missing. Is packaged in flatpak image all ?

### PR DESCRIPTION
**Pull request by valentindavid**
Should fix #155.

### CODE REVIEW

**Comment by nanonyme** [comment]
I think you're misinterpreting the error.  That error gets raised if .config is missing

**Comment by nanonyme** [comment]
I think we need to know why before fixing. It should get created through migrate_config()

**Comment by valentindavid** [comment]
I see. But where does `$XDG_CONFIG_HOME/.flatpak-info` get created?

**Comment by nanonyme** [comment]
shutil.copy2(...) is basically cp /.flatpak-info $XDG_CONFIG_HOME/.flatpak-info

**Pull request closed without merging**
