### PR TITLE
Allow bluetooth for Steam Controllers (#89)

### PR DESCRIPTION
**Pull request by ananace**

### CODE REVIEW

**Review by nanonyme — APPROVED** [review]
Looks plausible to me. Is this a no-op of Flatpak older than 0.11.8?

**Comment by ananace** [comment]
I am honestly not sure, and I have a feeling that the answer might be both 'yes' and 'no' depending of if talking about `flatpak` or `flatpak-builder`.

**Comment by nanonyme** [comment]
I was just discussing this on IRC and looks like old versions of Flatpak do not handle unrecognized allow switches safely https://github.com/flatpak/flatpak/commit/c8c0df3fba458844d99ddd773244467fa4a35408
Support came around 0.10.x

**Comment by nanonyme** [comment]
I'm going to merge this. At worst some people might have to install Flatpak from backports if they're using something ancient like Debian stable

**Pull request merged**
