### PR TITLE
gperftools: update to 2.8

### PR DESCRIPTION
**Pull request by Lctrs**

### CODE REVIEW

**Comment by nanonyme** [comment]
Did you check that the game is compatible with this?

**Comment by Lctrs** [comment]
Nope !

**Comment by Lctrs** [comment]
I don't own HL2 so I couldn't test with it, but I do own HL2: Deathmatch - which uses the same engine - and runned it without any issue with this commit.

**Comment by nanonyme** [comment]
Some of these bundled gperftools, some do not.

**Pull request merged**
