### PR TITLE
Zypak subsandbox

### PR DESCRIPTION
**Pull request by doraskayo**
This PR so far only adds Zypak to the sandbox for easier experimentation.

### CODE REVIEW

**Comment by nanonyme** [comment]
I think this is just the surface of the can of worms. We need to be able to launch pressure-vessel from inside zypak.

**Comment by doraskayo** [comment]
> I think this is just the surface of the can of worms. We need to be able to launch pressure-vessel from inside zypak.

More work is certainly needed, and it's still not clear where exactly. This PR so far only adds Zypak to the sandbox for easier experimentation.

I'm mostly waiting for comments on https://github.com/ValveSoftware/steam-for-linux/issues/8373#issuecomment-1030699670, with @smcv likely being a key person in deciding the direction this is going to take.

**Comment by smcv** [comment]
To avoid anyone having the wrong expectations: I do not have control over the proprietary parts of Steam, including steamwebhelper, and I do not have control over the timescale on which any change happens. I can make suggestions to Valve, but they will not necessarily implement them, and if they do, it will not necessarily be soon.

**Comment by smcv** [comment]
> I think this is just the surface of the can of worms. We need to be able to launch pressure-vessel from inside zypak.

I am going to experiment with enabling Zypak for just the steamwebhelper, and not the rest of Steam. If I can get that to work, then I can ask Valve people whether they'd be willing to autodetect a Flatpak environment and wrap the steamwebhelper (only!) in Zypak in that case.

**Comment by nanonyme** [comment]
@smcv is it possible for us as immediate mitigation to pass parameter to disable sandbox from wrapper script?

**Comment by smcv** [comment]
> @smcv is it possible for us as immediate mitigation to pass parameter to disable sandbox from wrapper script?

Yes, if you run `steam -no-cef-sandbox` that will disable this.

**Comment by smcv** [comment]
I'm also trying to get a change into the next Steam beta that will detect `/.flatpak-info` and automatically disable the sandboxing for now (equivalent to `-no-cef-sandbox`), which will put it back into the same situation that existed on the non-beta Steam branch.

**Comment by smcv** [comment]
> Yes, if you run `steam -no-cef-sandbox` that will disable this.

#867

**Comment by nanonyme** [comment]
Okay, let's have that be backup plan.

**Comment by smcv** [comment]
The issue addressed by this PR has been split out from https://github.com/ValveSoftware/steam-for-linux/issues/8373 and is now tracked as https://github.com/ValveSoftware/steam-for-linux/issues/8421.

**Pull request closed without merging**
