### PR TITLE
Feature/sdl wayland

### LINKED ISSUE #257: Expose Wayland by default
Currently Wayland socket is not exposed at all. Let's expose it *but* also clear sdl driver variable. This should make Wayland be used with SDL2 when it either becomes default or end user sets override.

### PR DESCRIPTION
**Pull request by nanonyme**
Closes #257 
@TingPing any opinions?

### CODE REVIEW

**Comment by nanonyme** [comment]
bot, build

**Comment by nanonyme** [comment]
bot, build

**Comment by TingPing** [comment]
I have my doubts that there won't be broken games because of this, but I don't know.

**Comment by nanonyme** [comment]
Yeah, that's possible, I guess. Maybe we should have a mechanism for masking the WAYLAND_DISPLAY for badly behaving apps (although basically all breakage I've seen thus far has been software where end-user forces Wayland on even when software doesn't properly support it) before turning this on. Then again, I guess really bad software could also be hardcoding wayland-0 but not really supporting Wayland correctly...

**Comment by nanonyme** [comment]
My idea was the main source of breakage would be end user setting SDL_DISPLAYDRIVER=wayland in their host and it leaking into the app which would result Wayland getting enabled when not really supported.

**Comment by nanonyme** [comment]
I'll leave this open in current form for now, should be easy to rebase if needed.

**Comment by TingPing** [comment]
> Hm, I guess there's also the thing that if some games break with Wayland exposed, they'd most likely currently be broken with native Steam already.

That is true and makes this more reasonable to try out.

**Comment by nanonyme** [comment]
bot, build

**Pull request merged**
