### PR TITLE
Fix NetworkManager talk-name

### PR DESCRIPTION
**Pull request by gasinvein**
NetworkManager is on system bus, so there should be `--system-talk-name` instead of `--talk-name`.

### CODE REVIEW

**Comment by gasinvein** [comment]
>What was the impact of this bug?

With `--socket=system-bus` nothing. Without it - no actual access to NetworkManager.

**Comment by nanonyme** [comment]
I mean, what broke?

**Comment by nanonyme** [comment]
This is just for historic purposes, I'm going to merge it anyway

**Comment by gasinvein** [comment]
As far as I know, Steam in `-steamos` mode use NM for network settings. In normal mode, it probably just gets info about current connections.

**Pull request merged**
