### PR TITLE
Release beta to stable

### PR DESCRIPTION
**Pull request by nanonyme**

### CODE REVIEW

**Comment by LoneFenris** [comment]
It looks like the version number may still need to be bumped (I'm guessing in metainfo.xml?). Flathub still shows 1.0.0.68 while it looks like this updates to 1.0.0.69.

**Comment by nanonyme** [comment]
Interesting. That's a bug in flatpak updater. Any chance of reporting it there? @gasinvein do you remember what the repo was?

**Comment by gasinvein** [comment]
Looks like flatpak-external-data-checker didn't update metainfo.xml for some reason. Please report it [here](https://github.com/flathub/flatpak-external-data-checker/issues).

**Comment by gasinvein** [comment]
Ah, I see. Opened #732

**Pull request merged**
