### PR TITLE
Propagate beta changes to stable

### PR DESCRIPTION
**Pull request by nanonyme**

### CODE REVIEW

**Comment by nanonyme** [comment]
@bbhtt any clue what this conflict is about?

**Comment by bbhtt** [comment]
It's in hwdata, I can't really edit these because the base is beta too. And the first few commits are already in master.

GitHub UI merge does not work well for these. Opened https://github.com/flathub/com.valvesoftware.Steam/pull/1349

**Comment by nanonyme** [comment]
Well, it used to and I have fixed this multiple times already. The problem is if anything is directly merged to master without going through beta, entire workflow breaks permanently.

**Comment by nanonyme** [comment]
The intent was to always do feature to beta to master to avoid beta and master diverging. Otherwise it's hard to say if all bug fixes are in all branches.

**Comment by bbhtt** [comment]
It is diverged already, because I did rebases before. Although I can probably abuse my admin privileges to fix that by force pushing.

**Comment by nanonyme** [comment]
Okay. Well, I'm no longer the maintainer so I don't really care. I was just explaining how the workflow was designed.

**Pull request closed without merging**
