### PR TITLE
Insert StartupWMClass into desktop entry

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by nanonyme** [comment]
Pattern looks odd. Is something missing?

**Comment by 9f565fdc** [comment]
The pattern means it will insert a new line containing the string `StartupWMClass=Steam` above the 11th line in the file `steam.desktop`.

**Comment by TingPing** [comment]
Use `desktop-file-edit` rather than `sed`.

**Comment by 9f565fdc** [comment]
I didn't know about `desktop-file-edit`, thank you. Updated.

**Pull request merged**
