### PR TITLE
Update to freedesktop 22.08

### PR DESCRIPTION
**Pull request by orowith2os**
It seems to be available now, so probably best to update it.

### CODE REVIEW

**Comment by orowith2os** [comment]
well that's interesting, because other apps are already using the 22.08 runtime from stable flathub.

**Comment by nanonyme** [comment]
It's not yet released

**Comment by orowith2os** [comment]
That's weird, because [there are other apps](https://github.com/flathub/dev.goats.xivlauncher/blob/master/dev.goats.xivlauncher.yml#L3) that are using it. I'll close this PR, then, since it doesn't seem to work.

**Comment by nanonyme** [comment]
I don't know what's going on, that shouldn't work. The runtime is still being published as 22.08beta.

**Pull request closed without merging**
