### PR TITLE
feat: remove tf2 workaround

### PR DESCRIPTION
**Pull request by dreamyukii**

### CODE REVIEW

**Comment by bbhtt** [comment]
Can you please provide some context here? Did Valve fix the issue? I see https://github.com/ValveSoftware/Source-1-Games/issues/5043 is still open?

**Comment by sekalengrengginang** [comment]
> Can you please provide some context here? Did Valve fix the issue? I see [ValveSoftware/Source-1-Games#5043](https://github.com/ValveSoftware/Source-1-Games/issues/5043) is still open?

Team Fortress 2 just recently got [updated](https://www.teamfortress.com/post.php?id=220436) to 64 bit and it no longer required workaround for libtcmalloc issue

**Comment by bbhtt** [comment]
bot, build

**Comment by bbhtt** [comment]
Thanks, seems to work for me.

**Comment by sekalengrengginang** [comment]
thank you

**Pull request merged**
