### PR TITLE
Add per-app-dev-shm into manifest

### PR DESCRIPTION
**Pull request by nanonyme**
Part of https://github.com/flatpak/flatpak/issues/3797

### CODE REVIEW

**Comment by nanonyme** [comment]
This will keep failing until Flathub gets new enough flatpak to support the new switch.

**Comment by smcv** [comment]
I was going to open this MR myself, thanks for getting there first!

The other possibility to make pressure-vessel work is `--device=shm`, but that weakens the sandbox (which is why I implemented `--allow=per-app-dev-shm`).

**Comment by nanonyme** [comment]
@smcv I asked from @barthalion yesterday, they said what goes to PPA goes into Flathub servers in a couple of days. So if newer flatpak can be made available on build servers, then let's just rebuild this. If not, we need to think of something else.

**Comment by nanonyme** [comment]
bot, build

**Comment by nanonyme** [comment]
Tested. While flatpak 1.10 does show the new permission, it is silently ignored. Iirc minimum requirement for silently ignoring is something a lot older than 1.00 which is our minimum requirement anyway.

**Pull request merged**
