### PR TITLE
Fix up skipping mounts

### PR DESCRIPTION
**Pull request by gasinvein**
Follow-up for #704

### CODE REVIEW

**Comment by nanonyme** [comment]
What kind of a case did this break?

**Comment by gasinvein** [comment]
2nd and further level subdirs weren't detected as mounts, e.g. `xdg-data/icons/hicolor` never matched `xdg-data` prefix.

**Comment by nanonyme** [comment]
Sorry but I don't get how normpath helps there.

**Comment by gasinvein** [comment]
It doesn't, it's for sanitizing the path just in case. Important thing is `filesystem_path.split('/')`, i.e. we split a string by slash.

**Pull request merged**
