### PR TITLE
Sync metainfo with upstream and add external game library notice

### PR DESCRIPTION
**Pull request by gasinvein**
Diverge less from the upstream metainfo.

Also adds a suggestion how to allow access to a game library on an external drive, as discussed on Matrix.

### CODE REVIEW

**Comment by AsciiWolf** [comment]
LGTM! This may also fix [this](https://gitlab.gnome.org/GNOME/gnome-software/-/issues/1528) GNOME Software issue. :-)

**Comment by gasinvein** [comment]
@AsciiWolf Looks like it didn't fix this?

**Comment by nanonyme** [comment]
Maybe not but it looked correct change anyway

**Comment by gasinvein** [comment]
Yes, the GS issue appears to be unrelated to metainfo, but to circular symlinks.

**Pull request merged**
