### PR TITLE
Migrate to 20.08

### PR DESCRIPTION
**Pull request by nanonyme**

### CODE REVIEW

**Comment by nanonyme** [comment]
bot, build

**Comment by gasinvein** [comment]
I see vkd3d fails to build. I might be a good idea to just drop it, it's not useful anymore anyway (Valve build their own incompatible fork for Proton, latest release 1.1 is just too old for anything).

**Comment by valentindavid** [comment]
For vkd3d I had success with: https://github.com/valentindavid/com.valvesoftware.Steam/commit/8b9a4b793aa5fae92fbfc4880b1bf71c202a945b

I am releasing beta.2 today which will fix nss so that the browser in Steam works again.

**Comment by gasinvein** [comment]
@valentindavid Now there is a hard-fork of vkd3d by Valve, specifically for Proton.

**Comment by valentindavid** [comment]
@gasinvein OK, we can switch to it.

**Comment by gasinvein** [comment]
@valentindavid I'd say it might be better to just drop it. Proton bundles it's own copy anyway.

**Comment by valentindavid** [comment]
@gasinvein All versions of proton?

**Comment by gasinvein** [comment]
@valentindavid At least since 4.11, and I'm not sure if previous versions even supported it.

**Comment by nanonyme** [comment]
Okay, I'll remove it. Thanks for comments.

**Comment by nanonyme** [comment]
Looking good. App will be entering bugfixes only mode once this is merged until 20.08 is out.

**Pull request merged**
