### PR TITLE
Allow user to override xdg paths

### LINKED ISSUE #683: Bad item [...] found in filesystem overrides
After the latest update I can no longer launch Steam due to the following error:

```
Bad item "xdg-config/gtk-3.0:ro" found in filesystem overrides
```

Yes, I do have such an override, and it's made on purpose for theming-related stuff.
I'm curious, why does the wrapper care about that, and why does it prevent Steam from starting?

### PR DESCRIPTION
**Pull request by nanonyme**
Fixes #683

### CODE REVIEW

**Comment by nanonyme** [comment]
Ping @gasinvein can you check this out? It seems to work correctly for me.

**Comment by gasinvein** [comment]
Before going into implementation details, I'd like to clarify the approach in general. If we just skip config/data/cache migration when there are fs overrides under it, migration won't be ever applied for users who added such overrides before first launch.
E.g. if user had `--filesystem=xdg-config/gtk-3.0` global override before installing Steam, `$XDG_CONFIG_HOME` and `~/.config` will stay as separate dirs for them until the override is removed. I'm not sure if this is what we want?

**Comment by nanonyme** [comment]
@gasinvein there is no separate dir. If you have the filesystem override, $XDG_CONFIG_HOME will point to ~/.config.

**Comment by nanonyme** [comment]
This is exactly why the migraions have been failing thus far. We were telling we want migration to be done from ~/.config to ~/.config. That will not end well for obvious reasons.

**Comment by nanonyme** [comment]
Okay, so the assumption was wrong. The paths are very much still original. I'm also really now suddenly a bit worried what happens if xdg-config path in host is config. We definitely should not migrate in that case.

**Pull request closed without merging**
