### PR TITLE
Add py2 shared module

### LINKED ISSUE #152: Proton Can't Launch
Valve's wine fork, Proton, which is part of the updated Steamplay, does not work. It cannot find /usr/bin/python2.7. despite the fact that it's there (sandbox permission perhaps?)

### PR DESCRIPTION
**Pull request by alatiera**
Close #152

### CODE REVIEW

**Comment by nanonyme** [comment]
bot, build

**Comment by nanonyme** [comment]
Looks like some permission denied in cleanup

**Comment by alatiera** [comment]
irc logs:

```sh
<alatiera> alexlarsson, hmm, stripping fails on the flathub runners too https://flathub.org/builds/#/builders/29/builds/463
<alexlarsson> alatiera: did you look for hardlinks?
<alexlarsson> I had similar issues with mesa/dri
<alexlarsson> all the driver .so are hardlinked as a megadriver
<alexlarsson> so, rofiles-fuse thinks you should not be allowed to modify it
<alexlarsson> Also, the strip-to-separate-file code embeds the filename into the stripped file, which breaks the symlinking
<alexlarsson> The fix there was to just manually strip that file
<alexlarsson> Can you try that?
<alexlarsson> alatiera: here: https://github.com/flatpak/freedesktop-sdk-images/blob/1.6/org.freedesktop.Sdk.json.in#L79
<alexlarsson> eh, not thats not it..
<alexlarsson> this: https://github.com/flatpak/freedesktop-sdk-images/blob/1.6/org.freedesktop.Sdk.json.in#L1507
<alatiera> alexlarsson, let me try, thanks!
<alexlarsson> alatiera: you can also look at the build results and see what is hardlinked to what
<alexlarsson> in a local build i mean
<alexlarsson> I mean, it could also be an *actual* permissions issue
<alexlarsson> i.e. where the make install didn't end with a "w" permission set on the file
```
I am investigating if its related to any hard link or indeed a permission error atm.

**Comment by alatiera** [comment]
Whats causing the issue is `--enable-shared` in the pyhon2 module config [here][1].

Adding a "post-install" cleanup section to the py2 module seems to fix it.
```json
    "post-install": [
        /* Theres seem to be a permissions missmatch that causes the debug stripping to fail */
        "chmod 644 /app/lib/libpython2.7.so.1.0"
    ],
```

I am not sure why, but I was able to built the flatpak correctly till now in a container. Only hit this issue with the system install.

I will followup with an MR against shared-modules.

[1]: https://github.com/flathub/shared-modules/blob/88bc0f633f45520998d50c38dc31295b46434b63/python2.7/python-2.7.15.json#L11

**Comment by nanonyme** [comment]
Please ping me with the PR

**Comment by nanonyme** [comment]
bot, build

**Comment by alatiera** [comment]
The submodule needs rebasing, no?

**Comment by alatiera** [comment]
Updated the sub module and also rebased the branch.

**Comment by nanonyme** [comment]
I'm considering merging this since test build passes but it's well possible it will take significant amount of time still before application build lands in Flathub. Previous build is still stalled waiting for almost an hour

**Pull request merged**
